### ISSUE TITLE
Initial Documentation

### ISSUE THREAD

**Issue by smeylan** [PatwinchIR/WordSense#11]
# Set up the Environment

For first set up, make a virtualenv with the requirements

`virtualenv -p <path to appropriate python> .`
`source bin/activate`
`pip install -r requirements.txt`

For working on the app thereafter, just run:

`source bin/activate`

Look on Heroku or ask project staff for env variables (there are many!)

Add these to `.profile` and source it (`source ~/.profile`)

# Copy Production Data to Local Postgres 

Get a postgres server running on your machine (e.g. postgres.app for OS X) 
Get a sql dump from Heroku or ask someone with access

FIXME @smeylan: Do we really want the --data only flag

`pg_dump --data-only postgres://<pg_user>:<pg_password>@<aws_host>:<port>/wordsense > wordsense_dump.sql`

FIXME @Dee: How to do (fake?) the migrations

# Start Django

In the virtual environment above, run:

`python manage.py runserver 0.0.0.0:5000`

Backend logging will continue in that terminal session

# Start Frontend

`yarn install` (may need to remove the babel library from the dev packages -- this might be because I've messed up my enviroment with another project)

`yarn run start` (this will open on port 3000; note that the app is hitting Django at 5000)

Frontend logging will continue in that terminal session

**Comment by PatwinchIR** [comment]
If it's data only, then we don't need to do "fake migrations". we can just do normal migrations on an empty psql database, then import the data
